{% set name = "boring-semantic-layer" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boringdata/boring-semantic-layer/archive/v{{ version }}.tar.gz
  sha256: 539f5c929e1edfedc517e7e813c7857fe8d94cf10f9daf0fd90628a3ae8b9af9

build:
  entry_points:
    - bsl = boring_semantic_layer.agents.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=25.3.0
    - packaging
    - pyyaml >=6.0
    - returns >=0.26.0
    - xorq >=0.3.4
    - ibis-framework >=11.0.0

test:
  imports:
    - boring_semantic_layer
  commands:
    - pip check
    - bsl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/boringdata/boring-semantic-layer
  summary: A boring semantic layer built with ibis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hb1915
    - boringdata
    - hachej
